// Shop Data - Local Version
// Replace imageUrl with actual shop logos in the images folder

var shopsData = [
    {
        id: 1,
        shopName: "Amazon",
        domain: "amazon.com",
        imageUrl: "images/shops/amazon.png",
        description: "Online shopping for electronics, apparel, computers, books, DVDs & more",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 2,
        shopName: "Walmart",
        domain: "walmart.com",
        imageUrl: "images/shops/walmart.png",
        description: "Save money. Live better.",
        countries: "US,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 3,
        shopName: "eBay",
        domain: "ebay.com",
        imageUrl: "images/shops/ebay.png",
        description: "Buy and sell electronics, cars, fashion apparel, collectibles, sporting goods",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 2.5,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 4,
        shopName: "Target",
        domain: "target.com",
        imageUrl: "images/shops/target.png",
        description: "Expect more. Pay less.",
        countries: "US,ALL",
        payPerSale: 3.5,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 5,
        shopName: "Best Buy",
        domain: "bestbuy.com",
        imageUrl: "images/shops/bestbuy.png",
        description: "Consumer electronics, computers, appliances, cell phones, video games & more",
        countries: "US,ALL",
        payPerSale: 2.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 6,
        shopName: "Booking.com",
        domain: "booking.com",
        imageUrl: "images/shops/booking.png",
        description: "Book hotels, homes, apartments and more",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 7,
        shopName: "Zalando",
        domain: "zalando.de",
        imageUrl: "images/shops/zalando.png",
        description: "Shoes and fashion online",
        countries: "DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 8,
        shopName: "ASOS",
        domain: "asos.com",
        imageUrl: "images/shops/asos.png",
        description: "Discover the latest fashion and trends in menswear and womenswear",
        countries: "GB,US,DE,FR,ALL",
        payPerSale: 6.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 9,
        shopName: "Nike",
        domain: "nike.com",
        imageUrl: "images/shops/nike.png",
        description: "Just Do It - Athletic footwear, apparel and equipment",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.5,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 10,
        shopName: "Adidas",
        domain: "adidas.com",
        imageUrl: "images/shops/adidas.png",
        description: "Impossible Is Nothing - Sports shoes, clothing and accessories",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 11,
        shopName: "H&M",
        domain: "hm.com",
        imageUrl: "images/shops/hm.png",
        description: "Fashion and quality at the best price",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.5,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 12,
        shopName: "Expedia",
        domain: "expedia.com",
        imageUrl: "images/shops/expedia.png",
        description: "Travel: Hotels, Flights, Car Rentals, Packages & more",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 3.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 13,
        shopName: "MediaMarkt",
        domain: "mediamarkt.de",
        imageUrl: "images/shops/mediamarkt.png",
        description: "Europe's largest consumer electronics retailer",
        countries: "DE,ALL",
        payPerSale: 2.5,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 14,
        shopName: "Otto",
        domain: "otto.de",
        imageUrl: "images/shops/otto.png",
        description: "Online shop for fashion, furniture, technology and more",
        countries: "DE,ALL",
        payPerSale: 5.5,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 15,
        shopName: "Currys",
        domain: "currys.co.uk",
        imageUrl: "images/shops/currys.png",
        description: "Electronics, TVs, Laptops, Appliances & more",
        countries: "GB,ALL",
        payPerSale: 2.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 16,
        shopName: "John Lewis",
        domain: "johnlewis.com",
        imageUrl: "images/shops/johnlewis.png",
        description: "Department Store - Fashion, Home & Garden, Electrical & more",
        countries: "GB,ALL",
        payPerSale: 3.5,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 17,
        shopName: "Fnac",
        domain: "fnac.com",
        imageUrl: "images/shops/fnac.png",
        description: "Electronics, computing, books, music, games and more",
        countries: "FR,ALL",
        payPerSale: 3.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 18,
        shopName: "Cdiscount",
        domain: "cdiscount.com",
        imageUrl: "images/shops/cdiscount.png",
        description: "French e-commerce website selling various products",
        countries: "FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 19,
        shopName: "Apple",
        domain: "apple.com",
        imageUrl: "images/shops/apple.png",
        description: "iPhone, iPad, Mac, Apple Watch, TV and more",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 1.5,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 20,
        shopName: "Samsung",
        domain: "samsung.com",
        imageUrl: "images/shops/samsung.png",
        description: "Mobile devices, TVs, home appliances and more",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 2.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 21,
        shopName: "Etsy",
        domain: "etsy.com",
        imageUrl: "images/shops/etsy.png",
        description: "Shop for handmade, vintage, custom, and unique gifts",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 22,
        shopName: "Wayfair",
        domain: "wayfair.com",
        imageUrl: "images/shops/wayfair.png",
        description: "Furniture, décor and more for every style and budget",
        countries: "US,GB,DE,ALL",
        payPerSale: 7.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 23,
        shopName: "Home Depot",
        domain: "homedepot.com",
        imageUrl: "images/shops/homedepot.png",
        description: "Home improvement supplies and building materials",
        countries: "US,ALL",
        payPerSale: 3.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 24,
        shopName: "IKEA",
        domain: "ikea.com",
        imageUrl: "images/shops/ikea.png",
        description: "Affordable furniture and home furnishing solutions",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 3.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 25,
        shopName: "Macy's",
        domain: "macys.com",
        imageUrl: "images/shops/macys.png",
        description: "Department store with clothing, shoes, accessories & more",
        countries: "US,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 26,
        shopName: "Nordstrom",
        domain: "nordstrom.com",
        imageUrl: "images/shops/nordstrom.png",
        description: "Fashion retailer offering clothing, shoes, and accessories",
        countries: "US,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 27,
        shopName: "Sephora",
        domain: "sephora.com",
        imageUrl: "images/shops/sephora.png",
        description: "Beauty products, makeup, skincare, hair care and fragrance",
        countries: "US,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 28,
        shopName: "Zara",
        domain: "zara.com",
        imageUrl: "images/shops/zara.png",
        description: "Latest trends in clothing, accessories and shoes for women, men and kids",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.5,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 29,
        shopName: "SHEIN",
        domain: "shein.com",
        imageUrl: "images/shops/shein.png",
        description: "Affordable trendy women's fashion and accessories",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 10.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 30,
        shopName: "AliExpress",
        domain: "aliexpress.com",
        imageUrl: "images/shops/aliexpress.png",
        description: "Online retail service with products from China and worldwide",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 31,
        shopName: "Costco",
        domain: "costco.com",
        imageUrl: "images/shops/costco.png",
        description: "Warehouse club with groceries, electronics, furniture and more",
        countries: "US,ALL",
        payPerSale: 2.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 32,
        shopName: "Lowe's",
        domain: "lowes.com",
        imageUrl: "images/shops/lowes.png",
        description: "Home improvement and appliances",
        countries: "US,ALL",
        payPerSale: 2.5,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 33,
        shopName: "Kohl's",
        domain: "kohls.com",
        imageUrl: "images/shops/kohls.png",
        description: "Department store with clothing, shoes, home & more",
        countries: "US,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 34,
        shopName: "Gap",
        domain: "gap.com",
        imageUrl: "images/shops/gap.png",
        description: "Casual clothing and accessories for men, women and children",
        countries: "US,GB,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 35,
        shopName: "Under Armour",
        domain: "underarmour.com",
        imageUrl: "images/shops/underarmour.png",
        description: "Athletic performance apparel, shoes and accessories",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 36,
        shopName: "Puma",
        domain: "puma.com",
        imageUrl: "images/shops/puma.png",
        description: "Sports shoes, clothing and accessories",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 37,
        shopName: "New Balance",
        domain: "newbalance.com",
        imageUrl: "images/shops/newbalance.png",
        description: "Athletic footwear and apparel",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 38,
        shopName: "Converse",
        domain: "converse.com",
        imageUrl: "images/shops/converse.png",
        description: "Classic sneakers and footwear",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 39,
        shopName: "Foot Locker",
        domain: "footlocker.com",
        imageUrl: "images/shops/footlocker.png",
        description: "Athletic footwear and apparel retailer",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 40,
        shopName: "JD Sports",
        domain: "jdsports.com",
        imageUrl: "images/shops/jdsports.png",
        description: "Sports fashion retailer",
        countries: "GB,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 41,
        shopName: "About You",
        domain: "aboutyou.de",
        imageUrl: "images/shops/aboutyou.png",
        description: "Online fashion store",
        countries: "DE,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "EUR"
    },
    {
        id: 42,
        shopName: "Boohoo",
        domain: "boohoo.com",
        imageUrl: "images/shops/boohoo.png",
        description: "Online fashion retailer",
        countries: "GB,US,ALL",
        payPerSale: 6.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 43,
        shopName: "Pretty Little Thing",
        domain: "prettylittlething.com",
        imageUrl: "images/shops/prettylittlething.png",
        description: "Women's fashion and accessories",
        countries: "GB,US,ALL",
        payPerSale: 6.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 44,
        shopName: "Missguided",
        domain: "missguided.com",
        imageUrl: "images/shops/missguided.png",
        description: "Women's fashion",
        countries: "GB,US,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 45,
        shopName: "ASOS Marketplace",
        domain: "marketplace.asos.com",
        imageUrl: "images/shops/asosmarketplace.png",
        description: "Vintage and independent fashion",
        countries: "GB,US,DE,FR,ALL",
        payPerSale: 4.0,
        payPerLead: 0,
        currency: "GBP"
    },
    {
        id: 46,
        shopName: "Farfetch",
        domain: "farfetch.com",
        imageUrl: "images/shops/farfetch.png",
        description: "Luxury fashion from boutiques around the world",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 47,
        shopName: "Net-a-Porter",
        domain: "net-a-porter.com",
        imageUrl: "images/shops/netaporter.png",
        description: "Luxury women's fashion",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    },
    {
        id: 48,
        shopName: "Mr Porter",
        domain: "mrporter.com",
        imageUrl: "images/shops/mrporter.png",
        description: "Luxury men's fashion",
        countries: "US,GB,DE,FR,ALL",
        payPerSale: 5.0,
        payPerLead: 0,
        currency: "USD"
    }
];
